on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: tests
    strategy:
      matrix:
        go-version: ['1.21.x']
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          cd back
          echo '${{ env.TESTE }}'
          go test ./service

    