on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: tests
    strategy:
      matrix:
        go-version: ['1.21.x']
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: test if docker is runnable
        run: |
          docker ps
      - run: echo ${{ vars.POSTGRE_URL }}
      - run: |
          cd back
          go test ./service
        env:
          TEST_POSTGRE_URL: ${{ vars.POSTGRE_URL }}

    